service: stepfunctions-test-branching

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev

functions:
  add:
    handler: handler.add
  double:
    handler: handler.double
  doubleBigNumber:
    handler: handler.doubleBigNumber

stepFunctions:
  stateMachines:
    simpleMaths:
      name: simple-maths
      definition:
        Comment: example to demonstrate function chaining
        StartAt: Add
        States:
          Add:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-add
            Next: IsBigNumber
          IsBigNumber:
            Type: Choice
            Choices:
              - Variable: $
                NumericGreaterThan: 50
                Next: DoubleBigNumber
            Default: Double
          Double:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-double
            End: true
            Retry:
              - ErrorEquals: [NumberIsTooBig]
                MaxAttempts: 0
              - ErrorEquals: [States.ALL]
                MaxAttempts: 3
            Catch:
              - ErrorEquals: [NumberIsTooBig]
                # Next: DefaultResponse
                Next: DoubleBigNumber
          # DefaultResponse:
          DoubleBigNumber:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-doubleBigNumber
            End: true
